//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetFood
    {
        public int feedID { get; set; }
        public Nullable<int> petID { get; set; }
        public Nullable<int> firmID { get; set; }
        public int kolMonth { get; set; }
        public int kolBig { get; set; }
        public int kolSmall { get; set; }
    
        public virtual FoodFirm FoodFirm { get; set; }
        public virtual PetPass PetPass { get; set; }
    }
}
